### ISSUE TITLE
Stream isolation

### ISSUE THREAD

**Issue by nam-shub** [EthACKdotOrg/orWall#20]
Right now, orWall sends all traffic to the same tor TransPort (9040, the default for orbot). This means that all activity, regardless of app, is tied together as it will likely end up on the same circuit. The exit node knows that this activity comes from the same user. So someones web browsing session can be tied to, say, their SIP identity if the SIP signaling is also tied to tor.

It would be really great if orWall could isolate streams by different apps, by using a different TransPort for each app allowed. This would require somehow adding a new TransPort directive to the tor config for each app.

**Comment by cjeanneret** [comment]
not really related to orWall, thus closing.

**Comment by JeremyRand** [comment]
Please re-open this issue; `IsolateDestAddr` and `IsolateDestPort` are *not* a substitute for per-app isolation, because they will not isolate 2 apps who connect to the same address/port.
