### ISSUE TITLE
Add non-root mode via VpnService

### ISSUE THREAD

**Issue by patcon** [EthACKdotOrg/orWall#39]
I think this was brought up somewhere else, but I thought it could be tracked in its own issue. I realize it's not high priority regardless.

https://stackoverflow.com/questions/20237743/android-firewall-with-vpnservice
### Considerations
- Wouldn't install init scripts, so communication would happen during boot.
- While it can be set to autostart on boot, a manual dialog is displayed that requires a confirmation warning with an "I trust this application" checkbox.

**Comment by dkumar1987** [comment]
Can someone help me to implement per app vpn?
I want to allow some specific applications(by default all) to pass through vpn.
It is a default API in lollipop version but I want to implement in below lollipop version.
How can i implement this? Please help me if someone has any idea.

**Comment by patcon** [comment]
Sorry @dkumar1987, but it's against all github and Internet etiquette to hijack a conversation with requests that have nothing to do with the project that everyone is here to talk about (orWall).

**Comment by n8fr8** [comment]
dkumar1987, Orbot now has VPN support, and will have per-app VPN soon. Otherwise, @patcon is right!!!
