### ISSUE TITLE
orWall blocking all traffic when using wireless data (wifi fine)

### ISSUE THREAD

**Issue by patcon** [EthACKdotOrg/orWall#45]
This was an issue before, and was the reason why I couldn't use orWall on my phone, and instead just used it on my wifi tablet. I'm unsure whether it was fixed at any point, or if I just forgot about it due to the widely available wifi where I am now :)

Anyhow, it definitely doesn't work on 0.20 and 0.19.

I didn't extensively test all interfaces yet, but I do know that `ifconfig wlan0` only works when wifi is enabled, and `ifconfig rmnet_usb0` only works when data is enabled. That's not conclusive, but at least it's some data points.

Just in case our interfaces are not the same:
(Again, I'm using a nexus 4)
```
root@mako:/ # ls /sys/class/net
dummy0
lo
p2p0
rev_rmnet0
rev_rmnet1
rev_rmnet2
rev_rmnet3
rev_rmnet4
rev_rmnet5
rev_rmnet6
rev_rmnet7
rev_rmnet8
rmnet0
rmnet1
rmnet2
rmnet3
rmnet4
rmnet5
rmnet6
rmnet7
rmnet_smux0
rmnet_usb0
rmnet_usb1
rmnet_usb2
rmnet_usb3
sit0
wlan0
```

**Comment by cjeanneret** [comment]
Any news in here? Else, I'll close it, as I'm unable to reproduce the problem on my own (nexus4 with CM is working just fine).
Small note though: try to restart Orbot when you switch your connection, it *might* be the root of the problem. Its stability has really improved lately, but still… ;)

**Comment by patcon** [comment]
Still an issue even after full wipe. I'm inclined to think it's probably something specific to my device for odd historical reasons that I won't go into. I've got a new wifi device that I'm transitioning onto anyhow, so it's a moot point :)

Thanks for everything!
