### ISSUE TITLE
orWall blocking Syncthing

### ISSUE THREAD

**Issue by Dreadeath** [EthACKdotOrg/orWall#65]
Syncthing app is working only if orWall is completely disabled. Well, I could start it only when I disabled orWall, otherwise it has eternal "Waiting for API" dialog window. My guess, problem is with localhost connection, Syncthing as I understood relies on 127.0.0.1:8080 server connections

Syncthing from f-droid:
https://f-droid.org/repository/browse/?fdid=com.nutomic.syncthingandroid

**Comment by Dreadeath** [comment]
Maybe add capability to directly input iptables rules or even run a script (like it was in Droidwall) after initialization of Orwall rules? So it will be universal workaround for similar issues.

**Comment by cjeanneret** [comment]
1.1.x should resolve that, as soon as we can make f-droid build it.
