### ISSUE TITLE
Batch rule changes into single superuser access request

### ISSUE THREAD

**Issue by patcon** [EthACKdotOrg/orWall#74]
Having done a lot of restarting while testing my other project, I can't help but think that all the superuser requests seem to be slowing things down. (It really does seem to slow my device down while rules are being applied, but maybe I'm crazy.) Also, it looks a little funny for the user to see all the root access toasts flashing at the bottom of the screen. Would be nice if it were just one, maybe?

Anyhow, having said all that, thanks for everything @cjeanneret! I post these tickets, but I really should be helping you out with this. Hopefully soon :)

**Comment by cjeanneret** [comment]
I already thought about that. Maybe group rules by chain or table. Have to see if the used lib supports batch mode, or something like that.

Thanks for the request, will give it a try when I have some spare time.

**Comment by cjeanneret** [comment]
Using libsupersu allows to pass array of strings:
```
List<String> Shell.SH.run(List<String> commands)
```

Need to dig a bit deeper, as orwall is using another lib (superuser-command).

**Comment by cjeanneret** [comment]
ok, seems we can do [that](https://github.com/EthACKdotOrg/superuser-commands/blob/6881993ebd2c0514f595711175bd850465a27352/libraries/RootCommands/src/main/java/org/sufficientlysecure/rootcommands/Shell.java#L312) in a smart way

**Comment by cjeanneret** [comment]
Hmm, there's a small issue if we put rules as a batch: we won't be able to get any precise output if something goes wrong.

For example, if a rule isn't applied, orWall won't be able to provide any decent output pointing the exact failing rule… This might be a bit annoying, especially seeing issues like #69… We wouldn't be able to spot the error as "missing system chain on this ROM"… Thus… might be a bit harder. I propose to post-pone this issue for now.

**Comment by patcon** [comment]
If i'm understanding you correctly, you're saying there are some iptables modifications for which their failure would have dependant failures, and it would be hard to distinguish?

It seems that after each command in the root shell (authorized only when first initiated), there is the opportunity to check exit codes and return values:
https://github.com/dschuermann/superuser-commands#simple-commands

That would address the concern, no? Of course, that might require some refactoring that personally challenge my own novice java chops, so I understand if that's the issue.

**Comment by cjeanneret** [comment]
more or less — just trying to create one root shell as class instance, should help a bit. Though it doesn't work straight away, of course ;).
Will find a solution, I guess this will be far better.

**Comment by cjeanneret** [comment]
Here it goes! 6f7c30691bb should alleviate a bit the stuff, though I'm pretty positive we can do even better than that. But not right now ;).

**Comment by patcon** [comment]
:heart:

**Comment by n8fr8** [comment]
Great!

**Comment by patcon** [comment]
Just restarted for first time after update, and no more crashes on startup! (was consistently doing so for months.) thanks!

**Comment by cjeanneret** [comment]
Good news then!

I might push some more corrections touching shell/sudo/commands as I think there is a new issue, though not really blocking nor visible.

I close this issue now ;-)
