### ISSUE TITLE
gradle config 

### ISSUE THREAD

**Issue by c3ph3us** [EthACKdotOrg/orWall#78]
it would be nice as you would write about how to build from source
I'm using android studio 1.2 x64 for Windows 

i'm trying to build and pufffff failure!
I don't have time to looking for dependences etc.

1) git clone .... OK!
2) gradlew.bat  -> frist problem 
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.   <- DONE
3) gradlew.bat  -> second one 
> Cannot evaluate module RootCommands : Configuration with name 'default' not found.

**Comment by cjeanneret** [comment]
Hello,

well, unfortunately, I'm no gradle guru… I just let android studio manage this part of the app :(. One thing is sure: it's doable outside of Studio, as f-droid is able to build it.

But I'm pretty sure you'll need to issue the following commands:
```Bash
git clone https://github.com/EthACKdotOrg/orWall.git
cd orWall
git submodule update --init
```

This should install the external modules, like RootCommands and other libs.

Hopefully this solves your issue.

Cheers,

C.

**Comment by c3ph3us** [comment]
C:\Users\ceph3us\AndroidStudioProjects\orWall>git submodule update --init
Submodule 'external/NetCipher' (git@github.com:EthACKdotOrg/NetCipher.git) regis
tered for path 'external/NetCipher'
Submodule 'external/i2p' (https://github.com/i2p/i2p.android.base.git) registere
d for path 'external/i2p'
Submodule 'external/super-commands' (git@github.com:ethackdotorg/superuser-comma
nds.git) registered for path 'external/super-commands'
Cloning into 'external/NetCipher'...
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to t
he list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:EthACKdotOrg/NetCipher.git' into submodule path 'extern
al/NetCipher' failed

**Comment by cjeanneret** [comment]
Darn… did I pushed ssh access for NetCipher ?! You might want, as a quick-fix, correct the .gitmodule file and set the HTTPS url instead. How does f-droid work in this case, mystery.

**Comment by c3ph3us** [comment]
u mean ?

	url = git@github.com:EthACKdotOrg/NetCipher.git
      ->  url = https://github.com/guardianproject/NetCipher
	
still 

Cloning into 'external/NetCipher'...	
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:EthACKdotOrg/NetCipher.git' into submodule path 'extern
al/NetCipher' failed

**Comment by cjeanneret** [comment]
you might want to clone from zero again, I corrected the remotes for submodules, and it seems to be working (just tested).

I close this issue, feel free to open a new one if you have other issues. Just for information, I'm no graddle guru, all was set up by Android Studio…
