### ISSUE TITLE
"LAN connections" setting either not working or I don't understand it

### ISSUE THREAD

**Issue by msiep** [EthACKdotOrg/orWall#83]
I've found with three different devices that the only way I can access addresses on my LAN (e.g., to use androidVNC to connect to a computer on my LAN when the phone is connected to the LAN WiFi) is to check "Allow this application to bypass Proxy" for that specific app. When I do that, it works even if "LAN connections" is set to Disabled. I'd prefer to allow access to LAN addresses without Tor while also requiring Tor for WAN addresses, and that is what I'd expect enabling "LAN connections" to do.  Any help with this issue much appreciated!

**Comment by cjeanneret** [comment]
Hello,

Did you try with IP or hostname? What android version? There are some issues with >4.3 due to changes at DNS management level (kernel resolver, spoofing uid as root, breaking dns filtering embedded in orwall…).

Any way to get your LAN subnet so that I can do some tests?

Cheers,

C.

**Comment by msiep** [comment]
I'm using IP not hostname and the subnet is 192.168.9.x.  The same thing happens with Android 4.2.2 (CyanogenMod 10.1.3-p3110) and Android 4.4.4 (CyanogenMod 11-20141112-SNAPSHOT-M12-jflte).

Thanks!

**Comment by msiep** [comment]
Update: I tried setting up hostnames (using the Hosts Editor app in F-Droid) for the IP addresses and that way enabling "LAN connections" works as I expected:  I can use androidVNC, for example, to connect to hostnames on my LAN, even with androidVNC not enabled at all in Orwall.

**Comment by msiep** [comment]
Another update: Using hostnames, it now seems to sometimes work and sometimes not.
