### ISSUE TITLE
project closed?

### ISSUE THREAD

**Issue by takiainen** [EthACKdotOrg/orWall#85]
Sorry to ask this here, but I couldn't find any other way to contact the developer. Just would like to know if orwall is still being developed? It is just a wonderful program, and would be a pity to see it go. There simply isn't another easy way to selectively route some programs through tor while letting some connect directly and finally preventing a big bunch of programs connecting to internet at all.  Afwall+ & orbot combination just doesn't seem to work.

**Comment by patcon** [comment]
I think @cjeanneret is just occupied with other things for the foreseeable future. (His main schtick isn't Android development, and he just learned while he built this.) But I think he should be responsive to solid pull requests. There are quite a few people still interested in this project, including some Guardian Project and Tor folks, so I don't think it's going anywhere.

Orbot has built-in routing, btw. Just not firm guarantees, as it using Android's builtin VpnService, which still leaks in some places like during boot. Orwall takes an intensive iptables approach at the OS level.

**Comment by cjeanneret** [comment]
Heya!

Nope, not dead, but as @patcon said, occupied with some other projects (which incidentally are more in my knowledge base…).
I'm dreaming of having some more time and knowledge in Android dev, but to be honest, it's not the case. 
Plus I'm still stuck with the SELinux issue (#77) — I hope to be able to solve this for christmas, as it's a really nasty issue :/.

To anyone: don't hesitate if you want to contribute to this project — I'm no Android guru, and I'm pretty sure there are things that can be done better.

Cheers,

C.
