### ISSUE TITLE
tcp6 connections go to clearnet

### ISSUE THREAD

**Issue by yurkobb** [EthACKdotOrg/orWall#88]
I've noticed that while normal ip v4 connections are routed trough Orbot as it should be, I see that apps can still make ip v6 connections to the clearnet. Here's an example of such connection (excerpt of network connections dump from OS Monitor - like netstat, but shows the app that's making the connection):
> TCP6,192.168.0.75:59272,52.11.123.60:443,ESTABLISHED,Fennec F-Droid

**Comment by cjeanneret** [comment]
hmm, yep, ipv6 isn't managed for now. Have to add the requested things so that it will call ip6tables in parallel.

Thanks for the heads-up — should be packed in the next release hopefully.

**Comment by hgourvest** [comment]
this commit https://github.com/EthACKdotOrg/orWall/pull/92/commits/ba03ea12cc75145a777d2fead3c13af415d8f588 fix this issue
