### ISSUE TITLE
F-droid unable to compile new release

### ISSUE THREAD

**Issue by cjeanneret** [EthACKdotOrg/orWall#98]
Hello @hgourvest,

seems f-droid is unable to compile the new release:
https://f-droid.org/wiki/page/org.ethack.orwall/lastbuild_38

Care to have a look and correct the gradle file if necessary?

Thanks?

**Comment by hgourvest** [comment]
I need to push things on this repos https://github.com/EthACKdotOrg/superuser-commands
to fix this issue
